package exeption;

import java.io.IOException;

public class Test {
    public static void main(String[] args) {
//        try {
//            System.out.println("Inside try-block");
//        }
//        catch(IOException e) { }
    }
}
